### PR TITLE
Fix docstring and border mode

### PR DESCRIPTION
**Pull request by dmadeka**
The docstring should be more Keras style - also the border mode is important. Keras 2 actually assumes valid instead of same.

See attached notebook for details

[Test+Conv1D.pdf](https://github.com/dmlc/keras/files/2060083/Test.Conv1D.pdf)

### CODE REVIEW

**Comment by dmadeka** [comment]
It would be nice to have a minor release :)

**Comment by dmadeka** [comment]
@piiswrong Could we also get a minor release?

**Comment by dmadeka** [comment]
@sandeep-krishnamurthy Just want to follow up on this

**Comment by dmadeka** [comment]
@piiswrong @sandeep-krishnamurthy Ping

**Comment by sandeep-krishnamurthy** [comment]
@piiswrong - Can you please merge this change?

**Pull request merged**
